version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ethcrawler?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - ETHERSCAN_API_KEY=IY6AIIRJPF7XX1B8NK9ZNS48JND3UUQF51
      - ETHERSCAN_API_URL=https://api.etherscan.io/api
      - OPENSEA_API_KEY=279cf63c382a4c589a5b2e7101362f41
    networks:
      - ethcrawler-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ethcrawler
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ethcrawler-network

networks:
  ethcrawler-network:
    driver: bridge

volumes:
  db-data: